<a href="https://colab.research.google.com/github/choidaesig/big_data_certificate/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
cd /content/drive/MyDrive/big_data_certificate

/content/drive/MyDrive/big_data_certificate


In [ ]:
!git clone https://choidaesig:study@github.com/choidaesig/big_data_certificate.git

fatal: destination path 'big_data_certificate' already exists and is not an empty directory.


In [ ]:
pwd

'/content/drive/MyDrive/big_data_certificate'

In [ ]:
import numpy as np

a1 = np.array([1,2,3])
print(a1)
print(type(a1))
print(a1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [ ]:
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)
print(a2.shape)

a3 = np.array([[1,2,3]])
print(a3)
print(a3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]]
(1, 3)


In [ ]:
# 배열의 차원 확인하기
print('array 1 : ',a1.ndim)
print('array 2 : ',a2.ndim)
print('array 3 : ',a3.ndim)


array 1 :  1
array 2 :  2
array 3 :  2


In [ ]:
# arange 함수 // 쉬운 배열구조 생성
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# np.arange(x,y,z) x값부터 y-1값까지 z값마큰 증가하는 배열 생성
a = np.arange(1,20,3)
print(a)

[ 1  4  7 10 13 16 19]


In [ ]:
# numpy 배열 초기화
zero_a = np.zeros((2,5))
one_a = np.ones((3,4))

print(zero_a)
print(one_a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 이미 생성된 구조를 유지하고 0으로 채우기
zero_b = np.zeros_like(one_a)
print(zero_b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# 이미 생성 구조에를 유지하고 1으로 채우기
one_b=np.ones_like(zero_a)
print(one_b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 특정 상수로 배열 생성
full_a = np.full((4,3),9)
random_a = np.random.random((3,4))

print(full_a)
print(random_a)


[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]
[[0.97858443 0.57766422 0.9219529  0.4048529 ]
 [0.01774664 0.85241644 0.76927031 0.28658468]
 [0.55671638 0.74294251 0.62480482 0.50942758]]


In [ ]:
# 넘파이 eye함수
eye_a = np.eye(4)
print(eye_a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# numpy 배열의 크기 변형

array = np.arange(12)
print('array1 : ', array)

array2 = array.reshape(3,4)
print('array2 : \n', array2)

array3 = array.reshape(3,4,order='F') # order='F' 선언 시 열부터 내용채운다.
print('array3 : \n', array3)

array1 :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
array2 : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array3 : 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [ ]:
# 1차원 변형 (flatten 함수)
array4 = array3.flatten()
print(array4)

[ 0  3  6  9  1  4  7 10  2  5  8 11]


In [ ]:
# 행렬 내적 (행렬 곱)
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8],[9,10],[11,12]])

dot_array = np.dot(array1,array2)
print(dot_array)

[[ 58  64]
 [139 154]]


In [ ]:
# 전치행렬 계산 (행과 열 위치를 교환한 원소로 구성한 행렬)

array1 = np.array([[1,2,3],[4,5,6]])
after = np.transpose(array1)
print('before \n',array1)
print('after \n',after)

before 
 [[1 2 3]
 [4 5 6]]
after 
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
len(after) # 배열 길이

3

In [ ]:
np.mean(after) # 평균
np.var(after) #분산
np.std(after) #표준편차

1.707825127659933